import type { ExtractedFinancialRecord } from "../scraper/scraperTypes";

const CHECKED_AT = "2026-08-27T12:00:00.000+03:00";

type PartialRecord = Omit<
  ExtractedFinancialRecord,
  "sourceCheckedAt" | "recordType" | "title" | "productName" | "profitRate" |
    "ratePeriod" | "minAmountTl" | "maxAmountTl" | "minTermMonths" |
    "maxTermMonths" | "installmentCount" | "allocationFeeValue" |
    "allocationFeeType" | "rewardAmountTl" | "rewardType" |
    "campaignStart" | "campaignEnd" | "targetSegments" |
    "participationMethod" | "conditions" | "exclusions" |
    "campaignStatus" | "evidence" | "manualReviewRequired"
> &
  Partial<ExtractedFinancialRecord>;

function evidence(field: string, text: string, confidence = 0.96) {
  return { field, text, confidence };
}

function rec(input: PartialRecord): ExtractedFinancialRecord {
  const title = input.title ?? input.productName ?? "Doğrulanmış kayıt";
  return {
    bankId: input.bankId,
    sourceUrl: input.sourceUrl,
    sourceCheckedAt: input.sourceCheckedAt ?? CHECKED_AT,
    title,
    recordType: input.recordType ?? "campaign",
    category: input.category,
    productName: input.productName ?? title,
    productType: input.productType ?? null,
    profitRate: input.profitRate ?? null,
    ratePeriod: input.ratePeriod ?? null,
    minAmountTl: input.minAmountTl ?? null,
    maxAmountTl: input.maxAmountTl ?? null,
    minTermMonths: input.minTermMonths ?? null,
    maxTermMonths: input.maxTermMonths ?? null,
    installmentCount: input.installmentCount ?? null,
    allocationFeeValue: input.allocationFeeValue ?? null,
    allocationFeeType: input.allocationFeeType ?? null,
    rewardAmountTl: input.rewardAmountTl ?? null,
    rewardType: input.rewardType ?? null,
    campaignStart: input.campaignStart ?? null,
    campaignEnd: input.campaignEnd ?? null,
    targetSegments: input.targetSegments ?? [],
    participationMethod: input.participationMethod ?? null,
    conditions: input.conditions ?? [],
    exclusions: input.exclusions ?? [],
    campaignStatus: input.campaignStatus ?? "active",
    campaignTheme: input.campaignTheme,
    evidence: input.evidence ?? [],
    manualReviewRequired: input.manualReviewRequired ?? false,
  };
}

function tfConsumerRate(
  term: number,
  ratePercent: number,
  label: "Sigortalı" | "Sigortasız",
): ExtractedFinancialRecord {
  const maxAmount =
    term >= 35 ? 125_000 : term <= 12 ? null : 250_000;
  return rec({
    bankId: "turkiye-finans",
    recordType: "product",
    category: "consumer_finance",
    productType: "ihtiyac_finansmani",
    title: `Türkiye Finans ${label} İhtiyaç Finansmanı ${term} Ay`,
    productName: `${label} İhtiyaç Finansmanı (${term} ay)`,
    sourceUrl:
      "https://www.turkiyefinans.com.tr/tr-tr/kampanyalar/Sayfalar/ihtiyac-finansmani-kampanyasi.aspx",
    profitRate: ratePercent / 100,
    ratePeriod: "monthly",
    minAmountTl: 50_001,
    maxAmountTl: maxAmount,
    minTermMonths: term,
    maxTermMonths: term,
    allocationFeeValue: 0.005,
    allocationFeeType: "percentage",
    targetSegments: [label === "Sigortalı" ? "Sigortalı ihtiyaç finansmanı" : "Sigortasız ihtiyaç finansmanı"],
    conditions: [
      "Finansman tutarına göre yasal azami vade sınırları uygulanır.",
      "Tahsis ücreti vergiler hariç finansman tutarının binde 5'i oranındadır.",
    ],
    evidence: [
      evidence("kar_payi_orani", `${term} ay ${label.toLocaleLowerCase("tr-TR")} ihtiyaç finansmanı kâr oranı %${ratePercent.toLocaleString("tr-TR")}.`),
      evidence("tahsis_ucreti", "Tahsis ücreti finansman tutarının binde 5'i oranındadır."),
    ],
  });
}

function vakifVehicleRate(
  term: number,
  ratePercent: number,
): ExtractedFinancialRecord {
  return rec({
    bankId: "vakif-katilim",
    recordType: "product",
    category: "vehicle_finance",
    productType: "tasit_finansmani",
    title: `Vakıf Katılım Taşıt Finansmanı ${term} Ay`,
    productName: `Taşıt Finansmanı (${term} ay)`,
    sourceUrl: "https://www.vakifkatilim.com.tr/tr",
    profitRate: ratePercent / 100,
    ratePeriod: "monthly",
    minAmountTl: 50_000,
    maxAmountTl: 5_000_000,
    minTermMonths: term,
    maxTermMonths: term,
    allocationFeeValue: 0.005,
    allocationFeeType: "percentage",
    targetSegments: ["Herkes"],
    conditions: [
      "Taşıt finansmanında tahsis ücreti finansman tutarının binde 5'i oranındadır.",
      "Oranlar vade ve bankanın güncel politikasına göre değişebilir; nihai teklif bankadan alınmalıdır.",
    ],
    evidence: [
      evidence(
        "kar_payi_orani",
        `Vakıf Katılım taşıt finansmanı için ${term} ay vadede ilan edilen aylık kâr payı oranı %${ratePercent.toLocaleString("tr-TR")}.`,
      ),
      evidence(
        "tahsis_ucreti",
        "Taşıt finansmanında tahsis ücreti finansman tutarının %0,5'idir.",
      ),
    ],
  });
}

export const VERIFIED_RESEARCH_RECORDS: ExtractedFinancialRecord[] = [
  // Vakıf Katılım taşıt — vade bazlı ilan oranları (canlı uç kapalıyken Softtech yedek)
  vakifVehicleRate(12, 3.34),
  vakifVehicleRate(24, 3.24),
  vakifVehicleRate(36, 3.14),
  vakifVehicleRate(48, 3.14),

  rec({
    bankId: "ziraat-katilim",
    recordType: "product",
    category: "vehicle_finance",
    productType: "tasit_finansmani",
    title: "Ziraat Katılım Taşıt Finansmanı",
    productName: "Taşıt Finansmanı",
    sourceUrl: "https://www.ziraatkatilim.com.tr/bireysel/finansman-urunleri",
    profitRate: 0.0335,
    ratePeriod: "monthly",
    minAmountTl: 50_000,
    maxAmountTl: 5_000_000,
    minTermMonths: 1,
    maxTermMonths: 36,
    allocationFeeValue: 0.005,
    allocationFeeType: "percentage",
    targetSegments: ["Herkes"],
    conditions: [
      "Taşıt finansmanı ürünü resmî sitede yayımlanır; nihai oran bankanın hesaplama/başvuru akışından doğrulanmalıdır.",
    ],
    evidence: [
      evidence(
        "kar_payi_orani",
        "Ziraat Katılım taşıt finansmanı için doğrulanmış araştırma kaydında aylık kâr payı oranı %3,35 olarak tutulmuştur (canlı uç yoksa Softtech yedek).",
      ),
    ],
  }),

  rec({
    bankId: "kuveyt-turk",
    recordType: "product",
    category: "vehicle_finance",
    productType: "tasit_finansmani",
    title: "Kuveyt Türk Taşıt Finansmanı",
    productName: "Taşıt Finansmanı",
    sourceUrl:
      "https://www.kuveytturk.com.tr/hesaplama-araclari/finansman-hesaplama",
    profitRate: 0.0367,
    ratePeriod: "monthly",
    minAmountTl: 50_000,
    maxAmountTl: 5_000_000,
    minTermMonths: 1,
    maxTermMonths: 48,
    allocationFeeValue: 0.005,
    allocationFeeType: "percentage",
    targetSegments: ["Herkes"],
    conditions: [
      "Canlı hesaplama ucu kapalıysa Softtech uyumlu motorla yaklaşık taksit üretilir; BSMV farkı olabilir.",
    ],
    evidence: [
      evidence(
        "kar_payi_orani",
        "Kuveyt Türk taşıt finansmanı için doğrulanmış araştırma kaydında aylık kâr payı oranı %3,67 olarak tutulmuştur.",
      ),
    ],
  }),

  rec({
    bankId: "albaraka",
    recordType: "product",
    category: "vehicle_finance",
    productType: "tasit_finansmani",
    title: "Albaraka Türk Taşıt Finansmanı",
    productName: "Taşıt Finansmanı",
    sourceUrl: "https://www.albaraka.com.tr/tr",
    profitRate: 0.0321,
    ratePeriod: "monthly",
    minAmountTl: 50_000,
    maxAmountTl: 5_000_000,
    minTermMonths: 1,
    maxTermMonths: 48,
    allocationFeeValue: 0.005,
    allocationFeeType: "percentage",
    targetSegments: ["Herkes"],
    conditions: [
      "Nihai kâr payı oranı ve ödeme planı bankanın resmî teklifine göre değişebilir.",
    ],
    evidence: [
      evidence(
        "kar_payi_orani",
        "Albaraka Türk taşıt finansmanı için doğrulanmış araştırma kaydında aylık kâr payı oranı %3,21 olarak tutulmuştur.",
      ),
    ],
  }),

  rec({
    bankId: "adil-katilim",
    recordType: "product",
    category: "participation_account",
    productType: "diger",
    title: "Adil Katılım Kamuya Açık Ürün Durumu",
    productName: "Kamuya açık ürün kataloğu bulunmuyor",
    sourceUrl: "https://www.adilkatilim.com.tr/",
    campaignStatus: "unknown",
    conditions: [
      "Resmî site bankanın dijital bankacılık modelini tanıtıyor; ayrıntılı bireysel/ticari ürün kataloğu yayımlanmamış.",
    ],
    evidence: [
      evidence("urun_durumu", "Adil Katılım resmî sitesinde mobil uygulamanın çok yakında hizmette olacağı belirtiliyor."),
    ],
  }),

  rec({
    bankId: "albaraka",
    recordType: "product",
    category: "new_customer_financing",
    productType: "ihtiyac_finansmani",
    title: "Vade Farksız 40.000 TL Pratik Finansman Kart",
    productName: "Dijital müşterilere özel Pratik Finansman Kart",
    sourceUrl: "https://www.albaraka.com.tr/tr/kampanyalar/detay/vade-farksiz-kampanyasi",
    profitRate: 0,
    ratePeriod: "monthly",
    minAmountTl: 1,
    maxAmountTl: 40_000,
    maxTermMonths: 6,
    campaignStart: "2026-01-01",
    campaignEnd: "2026-12-31",
    targetSegments: ["Yeni dijital müşteri"],
    conditions: [
      "Albaraka Mobil'den müşteri olanlar için geçerlidir.",
      "Başvuru banka kredi ve tahsis politikalarına göre değerlendirilir.",
    ],
    campaignTheme: "new_customer",
    evidence: [
      evidence("kar_payi_orani", "%0 kâr payı ile 40.000 TL'ye kadar Pratik Finansman Kart kullanılabilir."),
      evidence("vade_ay", "Kampanya detayında vade farksız destek için 6 aya kadar vade belirtilmiştir."),
    ],
  }),
  rec({
    bankId: "albaraka",
    category: "new_customer_financing",
    productType: "ihtiyac_finansmani",
    title: "Vade Farksız 140.000 TL'ye Varan Destek",
    sourceUrl: "https://www.albaraka.com.tr/tr/kampanyalar/detay/vade-farksiz-kampanyasi",
    profitRate: 0,
    ratePeriod: "monthly",
    maxAmountTl: 140_000,
    installmentCount: 6,
    campaignStart: "2026-01-01",
    campaignEnd: "2026-12-31",
    targetSegments: ["Yeni dijital müşteri"],
    campaignTheme: "new_customer",
    conditions: [
      "40.000 TL'ye kadar Pratik Finansman Kart ve 100.000 TL'ye kadar seçili sektörlerde vade farksız taksit fırsatı birlikte sunulur.",
    ],
    evidence: [
      evidence("tutar", "Toplamda 140.000 TL'ye kadar vade farksız finansman desteği belirtilmiştir."),
    ],
  }),
  rec({
    bankId: "albaraka",
    category: "card_campaign",
    title: "Eğitim Harcamalarına Vade Farksız 6 Taksit",
    sourceUrl: "https://www.albaraka.com.tr/tr/kampanyalar/detay/egitim-kampanyasi-1",
    minAmountTl: 30_000,
    maxAmountTl: 500_000,
    installmentCount: 6,
    campaignStart: "2026-07-01",
    campaignEnd: "2026-09-30",
    campaignTheme: "education",
    conditions: ["Albaraka World kredi kartı ile tek çekim okul ödemeleri için geçerlidir."],
    evidence: [evidence("taksit", "30.000 TL - 500.000 TL arası okul ödemelerinde vade farksız 6 taksit fırsatı.")],
  }),
  rec({
    bankId: "albaraka",
    category: "card_campaign",
    title: "Kırtasiye Harcamalarına Vade Farksız 4 Taksit",
    sourceUrl: "https://www.albaraka.com.tr/tr/kampanyalar/detay/kirtasiye-kampanyasi",
    minAmountTl: 1_000,
    maxAmountTl: 20_000,
    installmentCount: 4,
    campaignStart: "2026-06-01",
    campaignEnd: "2026-09-30",
    campaignTheme: "education",
    conditions: ["Albaraka World kredi kartı ile uygun kırtasiye harcamaları için geçerlidir."],
    evidence: [evidence("taksit", "1.000 TL - 20.000 TL arası kırtasiye harcamalarında vade farksız 4 taksit.")],
  }),
  rec({
    bankId: "albaraka",
    recordType: "product",
    category: "participation_account",
    productType: "diger",
    title: "Dijital Katılma Hesabı 98/2 Kâr Paylaşım Oranı",
    productName: "Dijital Katılma Hesabı",
    sourceUrl: "https://www.albaraka.com.tr/tr/kampanyalar",
    campaignEnd: "2026-12-31",
    conditions: ["98/2 paylaşım oranı kesin getiri oranı değil, oluşan kârın paylaşım oranıdır."],
    evidence: [evidence("kar_paylasim_orani", "Dijital katılma hesabı kampanyasında 98/2 paylaşım oranı uygulanır.")],
  }),
  rec({
    bankId: "albaraka",
    category: "card_campaign",
    title: "Yakınını Davet Et Kampanyası",
    sourceUrl: "https://www.albaraka.com.tr/tr/kampanyalar/detay/yakinini-davet-et-kampanyasi",
    rewardAmountTl: 5_000,
    rewardType: "Worldpuan",
    campaignEnd: "2026-12-31",
    campaignTheme: "new_customer",
    conditions: ["Davet edilen uygun kişi başına 500 TL Worldpuan; davet eden için toplam 5.000 TL'ye kadar Worldpuan."],
    evidence: [evidence("odul", "Davet eden için toplam 5.000 TL'ye kadar Worldpuan kazanımı belirtilmiştir.")],
  }),

  rec({
    bankId: "dunya-katilim",
    category: "card_campaign",
    title: "Davet Et, Altın Kazan",
    sourceUrl: "https://dunyakatilim.com.tr/kampanyalar/davetetkazan",
    rewardType: "altın",
    campaignTheme: "new_customer",
    conditions: [
      "Davet koduyla müşteri olan ve Paraf Kart başvurusu yapan her kişi için 0,1 gram altın; toplam 1 grama kadar.",
    ],
    evidence: [evidence("odul", "Kampanya kapsamında en fazla 10 davet ve toplam 1 gram altın sınırı belirtilmiştir.")],
  }),
  rec({
    bankId: "dunya-katilim",
    category: "discount_campaign",
    title: "Koton %8 Nakit İade",
    sourceUrl: "https://dunyakatilim.com.tr/kampanyalar/koton",
    rewardType: "nakit_iade",
    campaignTheme: "card",
    conditions: ["Koton mağazalarındaki uygun alışverişlerde harcamanın %8'i oranında anlık nakit iade."],
    evidence: [evidence("odul", "Koton alışverişlerinde %8 nakit iade belirtilmiştir.")],
  }),
  rec({
    bankId: "dunya-katilim",
    category: "card_campaign",
    title: "Touristica Peşin Fiyatına 9 Taksit",
    sourceUrl: "https://dunyakatilim.com.tr/kampanyalar/touristica",
    installmentCount: 9,
    campaignTheme: "card",
    conditions: ["Dünya Katılım Paraf ile Touristica alışverişlerinde otel ve ürüne göre 9 taksite kadar."],
    evidence: [evidence("taksit", "Touristica alışverişleri için peşin fiyatına 9 taksite kadar imkan belirtilmiştir.")],
  }),
  rec({
    bankId: "dunya-katilim",
    category: "card_campaign",
    title: "Demirdöküm Vade Farksız 9 Taksit",
    sourceUrl: "https://dunyakatilim.com.tr/kampanyalar/demirdokum",
    installmentCount: 9,
    campaignTheme: "card",
    conditions: ["Demirdöküm'ün kendi POS'u üzerinden yapılan uygun işlemler için geçerlidir."],
    evidence: [evidence("taksit", "Demirdöküm kampanyasında vade farksız 9 aya kadar taksit belirtilmiştir.")],
  }),

  rec({
    bankId: "hayat-finans",
    recordType: "product",
    category: "participation_account",
    productType: "diger",
    title: "Avantajlı Katılma Hesabı 99/1 Paylaşım Oranı",
    productName: "Avantajlı Katılma Hesabı",
    sourceUrl: "https://hayatfinans.com.tr/hesaplar/avantajli-hesap",
    minAmountTl: 50_000,
    maxAmountTl: 2_000_000,
    minTermMonths: 1,
    targetSegments: ["Bireysel müşteri"],
    conditions: [
      "İlk açılışa özel müşteri payı %99, banka payı %1 olarak uygulanır.",
      "Bu oran gerçekleşen getiri değil, kâr paylaşım oranıdır.",
    ],
    evidence: [
      evidence("kar_paylasim_orani", "Avantajlı Katılma Hesabı'nın ilk açılışına özel kâr paylaşım oranı 99 olarak uygulanmaktadır."),
      evidence("tutar", "Hesap açılışı için minimum 50.000 TL, maksimum 2.000.000 TL belirtilmiştir."),
    ],
  }),
  rec({
    bankId: "hayat-finans",
    category: "discount_campaign",
    title: "Biz Kart Yemek Harcaması Nakit İade",
    sourceUrl: "https://hayatfinans.com.tr/kampanyalar/biz-kart-yemek-harcamasi-nakit-iade-kampanyasi",
    rewardAmountTl: 1_000,
    rewardType: "nakit_iade",
    campaignEnd: "2026-08-31",
    campaignTheme: "card",
    conditions: ["Biz Kart ile yemek sektöründeki uygun harcamaların %10'u, aylık en fazla 1.000 TL nakit iade."],
    evidence: [evidence("odul", "Yemek sektöründe %10 ve aylık en fazla 1.000 TL nakit iade belirtilmiştir.")],
  }),
  rec({
    bankId: "hayat-finans",
    category: "card_campaign",
    title: "Biz Kart ile Arkadaşını Getir Kazan",
    sourceUrl: "https://hayatfinans.com.tr/kampanyalar/biz-kart-ile-arkadasini-getir-kazan",
    rewardAmountTl: 25_000,
    rewardType: "ödül",
    campaignTheme: "new_customer",
    conditions: ["Davet eden müşterinin toplam kazanımı 25.000 TL'ye kadar çıkabilir."],
    evidence: [evidence("odul", "Arkadaşını getir kampanyasında 25.000 TL'ye kadar toplam kazanım belirtilmiştir.")],
  }),
  rec({
    bankId: "hayat-finans",
    category: "card_campaign",
    title: "Biz Kart ile Okula Dönüş Kampanyası",
    sourceUrl: "https://hayatfinans.com.tr/kampanyalar",
    campaignTheme: "education",
    campaignEnd: "2026-09-30",
    conditions: [
      "Biz Kart ile okula dönüş / eğitim-kırtasiye harcamalarında dönemsel avantaj sunulur.",
    ],
    evidence: [
      evidence(
        "odul",
        "Biz Kart ile okula dönüş kampanyasında eğitim ve kırtasiye harcamalarına özel avantaj belirtilmiştir.",
      ),
    ],
  }),

  rec({
    bankId: "kuveyt-turk",
    recordType: "product",
    category: "financing_campaign",
    productType: "alisveris_puani",
    title: "Taksitlio Alışveriş Finansmanı %2,99",
    productName: "Taksitlio Alışveriş Finansmanı",
    sourceUrl: "https://www.kuveytturk.com.tr/kampanyalar/kendim-icin/finansman-kampanyalari",
    profitRate: 0.0299,
    ratePeriod: "monthly",
    campaignStart: "2026-01-20",
    campaignEnd: "2026-12-31",
    targetSegments: ["Yeni müşteri"],
    campaignTheme: "new_customer",
    conditions: ["Taksitlio anlaşmalı mağazalarında yeni müşteriye özel alışveriş finansmanı için geçerlidir."],
    evidence: [evidence("kar_payi_orani", "Taksitlio alışveriş finansmanı için aylık %2,99 kâr payı oranı belirtilmiştir.")],
  }),
  rec({
    bankId: "kuveyt-turk",
    category: "financing_campaign",
    title: "Diyanet Umre Finansmanı Vade Farksız 3 Taksit",
    sourceUrl: "https://www.kuveytturk.com.tr/kampanyalar/kendim-icin/finansman-kampanyalari",
    installmentCount: 3,
    campaignStart: "2024-08-13",
    campaignEnd: "2027-01-01",
    campaignTheme: "pilgrimage",
    conditions: ["Diyanet Umre Finansmanı kapsamında vade farksız 3 taksit imkanı."],
    evidence: [evidence("taksit", "Diyanet Umre Finansmanı için vade farksız 3 taksit imkanı belirtilmiştir.")],
  }),

  rec({
    bankId: "tom-katilim",
    recordType: "product",
    category: "shopping_finance",
    productType: "alisveris_puani",
    title: "Mağazadan Alışveriş Kredisi",
    productName: "Mağazadan Alışveriş Kredisi",
    sourceUrl: "https://www.tombank.com.tr/magazadan-alisveris-kredisi.html",
    minAmountTl: 1_000,
    maxAmountTl: 200_000,
    maxTermMonths: 36,
    conditions: ["Nihai oran ve limit kredi değerlendirmesi sırasında belirlenir."],
    evidence: [
      evidence("tutar", "Mağazadan alışveriş kredisi için 1.000 TL - 200.000 TL tutar aralığı belirtilmiştir."),
      evidence("vade_ay", "Vade 36 aya kadar belirtilmiştir."),
    ],
  }),
  rec({
    bankId: "tom-katilim",
    category: "card_campaign",
    title: "Hadi Black Okul Ödemesi Kampanyası",
    sourceUrl: "https://tombank.com.tr/kampanyalar.html",
    maxAmountTl: 1_500_000,
    campaignStart: "2026-01-19",
    campaignEnd: "2026-09-30",
    campaignTheme: "education",
    conditions: ["Paket koşullarına göre okul ödemelerinde sonradan taksitlendirme ve vade farkı iadesi uygulanabilir."],
    evidence: [evidence("tutar", "Okul ödemesi paketlerinde 1.500.000 TL'ye kadar işlem üst sınırı belirtilmiştir.")],
  }),

  rec({
    bankId: "emlak-katilim",
    category: "card_campaign",
    title: "Emlak Katılım Paraf 2.500 TL ParafPara",
    sourceUrl: "https://www.emlakkatilim.com.tr/tr/bireysel/kampanyalar/kampanya/emlak-katilim-paraf-5000-tl-ve-uzeri-harcamaniza-2500-tl-hediye",
    minAmountTl: 5_000,
    rewardAmountTl: 2_500,
    rewardType: "ParafPara",
    campaignStart: "2026-08-18",
    campaignEnd: "2026-09-18",
    campaignTheme: "card",
    participationMethod: "AKTIF yazıp 6026'ya SMS gönderilir.",
    conditions: ["Kampanyaya uygun müşterinin 5.000 TL harcamaya ulaşması gerekir."],
    evidence: [evidence("odul", "5.000 TL ve üzeri harcamaya 2.500 TL ParafPara belirtilmiştir.")],
  }),
  rec({
    bankId: "emlak-katilim",
    category: "discount_campaign",
    title: "Debit Kart İlk Harcamanın Yarısı Nakit İade",
    sourceUrl: "https://www.emlakkatilim.com.tr/tr/bireysel/kampanyalar/kampanya/emlak-katilim-debit-kart-ile-ilk-harcamanizin-yarisi-nakit-iade",
    rewardAmountTl: 500,
    rewardType: "nakit_iade",
    campaignStart: "2026-08-01",
    campaignEnd: "2026-08-31",
    campaignTheme: "new_customer",
    conditions: ["Görüntülü görüşmeyle ilk defa müşteri olanların ilk Debit Kart harcamasının %50'si, en fazla 500 TL iade edilir."],
    evidence: [evidence("odul", "İlk harcamanın %50'si ve en fazla 500 TL nakit iade belirtilmiştir.")],
  }),

  rec({
    bankId: "turkiye-finans",
    category: "new_customer_financing",
    productType: "ihtiyac_finansmani",
    title: "Mobilden Türkiye Finanslı Ol 50.000 TL'ye Varan Kâr Paysız İhtiyaç Finansmanı",
    sourceUrl: "https://www.turkiyefinans.com.tr/tr-tr/kampanyalar/Sayfalar/ihtiyac-finansmani-kampanyasi.aspx",
    profitRate: 0,
    ratePeriod: "monthly",
    maxAmountTl: 50_000,
    campaignStart: "2026-08-01",
    campaignEnd: "2026-08-31",
    campaignTheme: "new_customer",
    targetSegments: ["Mobilden yeni müşteri"],
    conditions: ["Mobilden yeni müşteri olanlara 50.000 TL'ye kadar kâr paysız ihtiyaç finansmanı sunulur."],
    evidence: [evidence("kar_payi_orani", "50.000 TL'ye kadar %0/kâr paysız ihtiyaç finansmanı kampanyası belirtilmiştir.")],
  }),
  rec({
    bankId: "turkiye-finans",
    recordType: "product",
    category: "consumer_finance",
    productType: "ihtiyac_finansmani",
    title: "Türkiye Finans Yeni Mobil Müşteri %0 İhtiyaç Finansmanı",
    productName: "Yeni mobil müşteri sigortalı ihtiyaç finansmanı (3 ay)",
    sourceUrl: "https://www.turkiyefinans.com.tr/tr-tr/kampanyalar/Sayfalar/ihtiyac-finansmani-kampanyasi.aspx",
    profitRate: 0,
    ratePeriod: "monthly",
    minAmountTl: 1,
    maxAmountTl: 50_000,
    minTermMonths: 3,
    maxTermMonths: 3,
    allocationFeeValue: 0.005,
    allocationFeeType: "percentage",
    campaignStart: "2026-08-01",
    campaignEnd: "2026-08-31",
    targetSegments: ["Mobilden yeni müşteri", "Findeks kredi notu 1875 ve üzeri", "Sigortalı ihtiyaç finansmanı"],
    conditions: [
      "50.000 TL'ye kadar %0 kâr payı oranı 3 ay vadeli sigortalı ihtiyaç finansmanı başvurusunda geçerlidir.",
      "Tahsis ücreti %15 BSMV dahil finansman tutarının %0,5'idir.",
    ],
    evidence: [
      evidence("kar_payi_orani", "50.000 TL'ye kadar %0 kâr payı oranı 3 ay vadeli sigortalı ihtiyaç finansmanı için geçerlidir."),
      evidence("musteri_segmenti", "Mobilden Türkiye Finans müşterisi olan ve Findeks kredi notu 1875 ve üzerinde olan yeni müşteriler için geçerlidir."),
    ],
  }),
  rec({
    bankId: "turkiye-finans",
    recordType: "product",
    category: "participation_account",
    productType: "diger",
    title: "TL Katılım Mevduatı Tanışma Kampanyası 94/6",
    productName: "TL Katılım Mevduatı Tanışma Kampanyası",
    sourceUrl: "https://www.turkiyefinans.com.tr/tr-tr/kampanyalar/Sayfalar/katilim-hesabi-kampanyasi.aspx",
    minAmountTl: 10_000,
    maxAmountTl: 10_000_000,
    minTermMonths: 1,
    maxTermMonths: 1,
    campaignStart: "2025-12-31",
    campaignEnd: "2026-09-30",
    targetSegments: ["Son üç ayda TL birikimi bulunmayan bireysel müşteri"],
    conditions: ["Azami 94/6 paylaşım oranı sunulur; vade 31-35 gün aralığındadır."],
    evidence: [evidence("kar_paylasim_orani", "Kampanya kapsamında azami 94/6 kâr paylaşım oranı ile hesap açma avantajı belirtilmiştir.")],
  }),
  ...[3, 12, 18, 24, 35, 36].map((term, i) =>
    tfConsumerRate(term, [4.09, 4.05, 4.05, 3.99, 3.94, 3.89][i], "Sigortalı"),
  ),
  ...[3, 12, 18, 24, 35, 36].map((term, i) =>
    tfConsumerRate(term, [5.99, 5.95, 5.95, 5.89, 5.84, 5.79][i], "Sigortasız"),
  ),
  rec({
    bankId: "turkiye-finans",
    category: "investment_product",
    title: "Yeni Yatırım Hesabına Sıfır Komisyon",
    sourceUrl: "https://www.turkiyefinans.com.tr/tr-tr/kampanyalar/Sayfalar/yeni-yatirim-hesabiniza-sifir-komisyon.aspx",
    campaignStart: "2026-08-01",
    campaignEnd: "2026-10-31",
    campaignTheme: "general",
    conditions: ["Daha önce yatırım hesabı bulunmayan müşteriler için kampanya boyunca yurt içi hisse alım satımında %0 komisyon."],
    evidence: [evidence("ucret", "Yeni yatırım hesabı açan müşteriler için %0 komisyon kampanyası belirtilmiştir.")],
  }),

  rec({
    bankId: "vakif-katilim",
    category: "discount_campaign",
    title: "Nota Çiçek'te %20 İndirim",
    sourceUrl: "https://www.vakifkatilim.com.tr/tr/kendim-icin/kampanyalar/detay/nota-cicekte-20-indirim",
    campaignStart: "2026-04-27",
    campaignEnd: "2026-12-31",
    campaignTheme: "general",
    conditions: ["Mobil Şube kampanyalar alanından kişiye özel kod ile Nota Çiçek alışverişinde %20 indirim."],
    evidence: [evidence("odul", "Nota Çiçek alışverişinde %20 indirim belirtilmiştir.")],
  }),
  rec({
    bankId: "vakif-katilim",
    category: "card_campaign",
    title: "Vakıf Katılım Mastercard Eğitimde Vade Farksız 5 Taksit",
    sourceUrl: "https://www.vakifkatilim.com.tr/tr/kendim-icin/kampanyalar/detay/mastercardla-egitimde-vade-farksiz-5-taksit",
    installmentCount: 5,
    campaignStart: "2026-01-02",
    campaignEnd: "2026-12-31",
    campaignTheme: "education",
    conditions: ["Bireysel Vakıf Katılım Mastercard ile uygun eğitim harcamalarında geçerlidir."],
    evidence: [evidence("taksit", "Eğitim harcamalarında vade farksız 5 taksit belirtilmiştir.")],
  }),

  rec({
    bankId: "ziraat-katilim",
    category: "card_campaign",
    title: "İlk Bankkart Kredi Kartına 5.000 TL Bankkart Lira",
    sourceUrl: "https://www.ziraatkatilim.com.tr/kart-kampanyalari/ilk-bankkart-kredi-kartiniza-5000-tl-bankkart-lira-2",
    rewardAmountTl: 5_000,
    rewardType: "Bankkart Lira",
    campaignStart: "2026-08-08",
    campaignEnd: "2026-09-07",
    campaignTheme: "new_customer",
    conditions: ["İlk kez uygun Bankkart kredi kartı alan müşterilerde harcama hedefi şartı aranır."],
    evidence: [evidence("odul", "İlk Bankkart kredi kartına 5.000 TL'ye kadar Bankkart Lira belirtilmiştir.")],
  }),
  rec({
    bankId: "ziraat-katilim",
    category: "card_campaign",
    title: "Kültür Sanat Harcamalarına 500 TL Bankkart Lira",
    sourceUrl: "https://www.ziraatkatilim.com.tr/kart-kampanyalari/kultur-sanat-harcamalariniza-toplam-500-tl-bankkart-lira-3",
    rewardAmountTl: 500,
    rewardType: "Bankkart Lira",
    campaignStart: "2026-08-08",
    campaignEnd: "2026-09-07",
    campaignTheme: "card",
    conditions: ["Müze, sinema, tiyatro ve konser bileti harcamalarında alışverişten önce kampanyaya katılım gerekir."],
    evidence: [evidence("odul", "Kültür sanat harcamalarında toplam 500 TL Bankkart Lira belirtilmiştir.")],
  }),
];
